# themes from https://github.com/alacritty/alacritty-theme

import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 7
y = 7

[colors.cursor]
cursor = "0xebdbb2"
