# themes from https://github.com/alacritty/alacritty-theme

import = ["~/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.offset]
y = 4

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[font.bold]
family = "FiraMono Nerd Font"
style = "Regular"

[font.italic]
family = "FiraMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "FiraMono Nerd Font"
style = "Regular"

[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[colors.cursor]
# cursor = "0xebdbb2"

[keyboard]
bindings = [
  { key="C", mods="Command", chars="\u0003"},
  { key = "S", mods = "Command", chars = "\u0013" },
  { key = "F", mods = "Command", chars = "\u0006" }
]

